global:
  slack_api_url: 'https://hooks.slack.com/services/...'

route:
  receiver: slack-notifier
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 2m

receivers:
  - name: slack-notifier
    slack_configs:
      - channel: '#alerts'
        send_resolved: true
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ .CommonAnnotations.description }}"
